### PR TITLE
iTunes baseUri manipulation for test purposes

### PR DESCRIPTION
**Pull request by aliozkan**

### CODE REVIEW

**Comment by Stafox** [comment]
Hi. What you trying to achieve with that change?
Why you won't to use `setEndpoint()` method for that?

**Comment by aliozkan** [comment]
`setEndpoint()` is checking if endpoint is production or sandbox, otherwise it throws InvalidArgumentException:

```
public function setEndpoint(string $endpoint): self
    {
        if ($endpoint !== self::ENDPOINT_PRODUCTION && $endpoint !== self::ENDPOINT_SANDBOX) {
            throw new InvalidArgumentException("Invalid endpoint '{$endpoint}'");
        }
        $this->endpoint = $endpoint;

        return $this;
    }
```

**Comment by Stafox** [comment]
Correct. What endpoint you want to specify beside prod/sandbox?

**Comment by aliozkan** [comment]
Custom endpoint that simulates Apple `/verifyReceipt` endpoint. Returns success/error response based on `receipt-data` input. We can run integration tests with our specific `receipt-data` and get success/error response without any client involved.

**Comment by Stafox** [comment]
Available in [4.4.3](https://github.com/aporat/store-receipt-validator/releases/tag/4.4.3)

**Pull request merged**
