### PR TITLE
Add possibility to get promotional offer id.

### PR DESCRIPTION
**Pull request by Stafox**
Apple has added support for promotinal offers: https://developer.apple.com/documentation/storekit/in-app_purchase/implementing_subscription_offers_in_your_app

This pull request adds possibility to get promotional offer id for transaction

### CODE REVIEW

**Comment by Stafox** [comment]
@aporat merge needed.

**Comment by yaronius** [comment]
@aporat any updates on this?

**Comment by Stafox** [comment]
@yaronius As a workaround you can get the RawResponse, and get this field there.

**Comment by aporat** [comment]
sorry for the delay. merged! thanks @Stafox

**Pull request merged**
