### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Using the `php-nightly` test rather than `php-master`.
- Since the minimum version is `php-7.1`, we can use the native `void` type hint directly.
- To let classes on `tests` folder be consistency for PHP file name, let they've the same name.
- To let one class be one file name, the `DummyCache` class should be another file.
- Define `require-dev` block to organize these classes on `tests` folder and it can let them load automatically via Composer autoloader.

### CODE REVIEW

**Comment by Stafox** [comment]
@peter279k why have you dropped the nesbot/carbon 1.0 support?

**Comment by peter279k** [comment]
According to this discussion https://github.com/laravel/framework/issues/28679, the Carbon 1.x is deprecated.

I think we don't have to set the abandoned dependencies.

**Comment by Stafox** [comment]
@peter279k if there are no heavy needs to drop support, we should not to do that. Espeacially, if it just a test refactoring, because it will require major version update according to semver. 

In my mind we should remove a dependency of carbon for this library at all.

**Comment by peter279k** [comment]
> @peter279k if there are no heavy needs to drop support, we should not to do that. Espeacially, if it just a test refactoring, because it will require major version update according to semver.
> 
> In my mind we should remove a dependency of carbon for this library at all.

Ok. I agree with you, reverting this. And I think it's another PR.

**Comment by aporat** [comment]
thanks! merged

**Pull request merged**
